name: isohttpd
description: A lightweight http server that runs in an isolate. Router and logs are included.
version: 0.5.0
homepage: https://github.com/synw/isohttpd

environment:
  sdk: ^3.5.4

dev_dependencies:
  test: 

dependencies:
  pedantic: 
  extra_pedantic: 
  meta: 
  # body_parser: ^1.1.1
  iso: 
  path: 
  emodebug: 
